GET http://localhost:5000/api/auth

###

POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "username": "lybinh",
    "password": "123"
}

###
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "lybinh",
    "password": "123"
}

###
POST http://localhost:5000/api/posts/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzc3MDdlYTJkY2FhOGQxNWYyYTExZmEiLCJpYXQiOjE2Njg3NjA0NTR9.FCchTCdo0lzzc5X0MCwh0jJEfrMyRnLGmX5KfWN9HM8

{
    "title": "Learn Morgan",
    "description": "Framework for Nodejs",
    "url": "morgan.com",
    "status": "LEARNING"
}

###
GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzc3MDdlYTJkY2FhOGQxNWYyYTExZmEiLCJpYXQiOjE2Njg3NjA0NTR9.FCchTCdo0lzzc5X0MCwh0jJEfrMyRnLGmX5KfWN9HM8

###
PUT http://localhost:5000/api/posts/update/637743c2f1f5985c46ec1b89
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Mzc3MDdlYTJkY2FhOGQxNWYyYTExZmEiLCJpYXQiOjE2Njg3NjQ0NDJ9.YyaUR8kuwogUIwA43wk1y5NDO1Yi3QlHGBvlZkPuBCU

{
    "title": "Learn Morgan updated",
    "description": "Framework for Nodejs",
    "url": "",
    "status": "LEARNED"
}

